/** Tailwind config — design tokens via CSS variables (Steps 1-5). */
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "var(--color-brand-50)",
          100: "var(--color-brand-100)",
          200: "var(--color-brand-200)",
          300: "var(--color-brand-300)",
          400: "var(--color-brand-400)",
          500: "var(--color-brand-500)",
          600: "var(--color-brand-600)",
          700: "var(--color-brand-700)",
          800: "var(--color-brand-800)",
          900: "var(--color-brand-900)",
          950: "var(--color-brand-950)",
        },
        stone: {
          50: "var(--color-stone-50)",
          100: "var(--color-stone-100)",
          200: "var(--color-stone-200)",
          300: "var(--color-stone-300)",
          400: "var(--color-stone-400)",
          500: "var(--color-stone-500)",
          600: "var(--color-stone-600)",
          700: "var(--color-stone-700)",
          800: "var(--color-stone-800)",
          900: "var(--color-stone-900)",
        },
        enterprise: {
          earth: "var(--color-earth)",
          "earth-50": "var(--color-earth-50)",
          soil: "var(--color-soil-beige)",
          "soil-50": "var(--color-soil-50)",
          sky: "var(--color-sky)",
          "sky-50": "var(--color-sky-50)",
          ai: "var(--color-ai-indigo)",
          "ai-light": "var(--color-ai-indigo-light)",
          warning: "var(--color-warning)",
          critical: "var(--color-critical)",
          neutral: "var(--color-neutral-bg)",
          dark: "var(--color-dark-enterprise)",
        },
        surface: {
          bg: "var(--color-surface-bg)",
          card: "var(--color-surface-card)",
          border: "var(--color-surface-border)",
          muted: "var(--color-surface-muted)",
        },
        orange: {
          50: "var(--color-orange-50)",
          600: "var(--color-orange-600)",
        },
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        card: "var(--radius-card)",
        button: "var(--radius-button)",
        chip: "var(--radius-chip)",
        iconBox: "var(--radius-iconBox)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        card: "var(--shadow-card)",
        cardHover: "var(--shadow-cardHover)",
        button: "var(--shadow-button)",
      },
      fontSize: {
        xs: ["11px", { lineHeight: "16px", letterSpacing: "0.01em" }],
        sm: ["13px", { lineHeight: "18px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["28px", { lineHeight: "36px" }],
      },
    },
  },
  plugins: [],
};
